// <auto-generated />
using System;
using LegalConnect.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LegalConnect.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260308154007_AddCaseStaffPermissions")]
    partial class AddCaseStaffPermissions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LegalConnect.API.Entities.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePictureUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("LegalConnect.API.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ClientProfileId")
                        .HasColumnType("int");

                    b.Property<decimal>("ConsultationFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("LawyerProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("PlatformCommission")
                        .HasColumnType("decimal(18,2)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClientProfileId");

                    b.HasIndex("LawyerProfileId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.Case", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<string>("CaseNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CaseTitle")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("CaseType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ClientProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Court")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DealId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<DateTime?>("FilingDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("LawyerClientId")
                        .HasColumnType("int");

                    b.Property<int?>("LawyerProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NextHearingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Outcome")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("ClientProfileId");

                    b.HasIndex("DealId");

                    b.HasIndex("LawyerClientId");

                    b.HasIndex("LawyerProfileId");

                    b.ToTable("Cases");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.CaseActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActivityDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CreatedByRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("CaseActivities");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.CaseActivityDocument", b =>
                {
                    b.Property<int>("CaseActivityId")
                        .HasColumnType("int");

                    b.Property<int>("CaseDocumentId")
                        .HasColumnType("int");

                    b.HasKey("CaseActivityId", "CaseDocumentId");

                    b.HasIndex("CaseDocumentId");

                    b.ToTable("CaseActivityDocuments");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.CaseDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("bit");

                    b.Property<bool>("SharedWithAllLawyers")
                        .HasColumnType("bit");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UploadedByRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UploadedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CaseId");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("CaseDocuments");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.CaseDocumentLawyerShare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CaseDocumentId")
                        .HasColumnType("int");

                    b.Property<int>("LawyerProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LawyerProfileId");

                    b.HasIndex("CaseDocumentId", "LawyerProfileId")
                        .IsUnique();

                    b.ToTable("CaseDocumentLawyerShares");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.CaseLawyer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AddedByRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LawyerProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LawyerProfileId");

                    b.HasIndex("CaseId", "LawyerProfileId")
                        .IsUnique();

                    b.ToTable("CaseLawyers");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.CaseResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CaseTitle")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Court")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("LawyerProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LawyerProfileId");

                    b.ToTable("CaseResults");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.CaseStaff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("AddedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("StaffProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StaffProfileId");

                    b.HasIndex("CaseId", "StaffProfileId")
                        .IsUnique();

                    b.ToTable("CaseStaffs");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("IconClass")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Criminal defense and prosecution",
                            IconClass = "bi bi-shield",
                            IsActive = true,
                            Name = "Criminal Law"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Divorce, custody, adoption",
                            IconClass = "bi bi-people",
                            IsActive = true,
                            Name = "Family Law"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Business and corporate legal services",
                            IconClass = "bi bi-building",
                            IsActive = true,
                            Name = "Corporate Law"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Civil disputes and litigation",
                            IconClass = "bi bi-file-text",
                            IsActive = true,
                            Name = "Civil Law"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Real estate and property matters",
                            IconClass = "bi bi-house",
                            IsActive = true,
                            Name = "Property Law"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Employment and labour disputes",
                            IconClass = "bi bi-briefcase",
                            IsActive = true,
                            Name = "Labour Law"
                        });
                });

            modelBuilder.Entity("LegalConnect.API.Entities.Certification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CertificateUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("IssuingOrganization")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("LawyerProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LawyerProfileId");

                    b.ToTable("Certifications");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.ClientLawyerRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LawyerNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("LawyerProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LawyerProfileId");

                    b.HasIndex("ClientProfileId", "LawyerProfileId")
                        .IsUnique();

                    b.ToTable("ClientLawyerRequests");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.ClientProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ClientProfiles");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.CommissionSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DefaultCommissionPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("CommissionSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DefaultCommissionPercentage = 10m,
                            LastUpdatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("LegalConnect.API.Entities.Deal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("HireRequestId")
                        .HasColumnType("int");

                    b.Property<int>("LawyerProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientProfileId");

                    b.HasIndex("HireRequestId")
                        .IsUnique();

                    b.HasIndex("LawyerProfileId");

                    b.ToTable("Deals");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.Experience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<int>("LawyerProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Organization")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("LawyerProfileId");

                    b.ToTable("Experiences");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.HireRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CaseType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ClientProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Court")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LawyerProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientProfileId");

                    b.HasIndex("LawyerProfileId");

                    b.ToTable("HireRequests");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.HireRequestMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("HireRequestId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("SenderRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SenderUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HireRequestId");

                    b.HasIndex("SenderUserId");

                    b.ToTable("HireRequestMessages");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ChargeType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DealId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("GstAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GstRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("ProposalId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DealId");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique();

                    b.HasIndex("ProposalId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.LawyerBlackoutBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("LawyerProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RecurringPattern")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LawyerProfileId", "DayOfWeek");

                    b.ToTable("LawyerBlackoutBlocks");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.LawyerClient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ClientProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FirstAppointmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LawyerProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ClientProfileId");

                    b.HasIndex("FirstAppointmentId");

                    b.HasIndex("LawyerProfileId", "ClientProfileId")
                        .IsUnique();

                    b.ToTable("LawyerClients");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.LawyerHolidayPreference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("LawyerProfileId")
                        .HasColumnType("int");

                    b.Property<int>("MasterHolidayId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MasterHolidayId");

                    b.HasIndex("LawyerProfileId", "MasterHolidayId")
                        .IsUnique();

                    b.ToTable("LawyerHolidayPreferences");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.LawyerInvoiceSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorizedSignImagePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("BankDetails")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FirmAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FirmLogoPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FirmName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("GSTNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("LawyerProfileId")
                        .HasColumnType("int");

                    b.Property<string>("NotesForInvoice")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PostalCode")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("State")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TermsAndConditions")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Website")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("LawyerProfileId")
                        .IsUnique();

                    b.ToTable("LawyerInvoiceSettings");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.LawyerPersonalHoliday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HolidayDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LawyerProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RecurringPattern")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LawyerProfileId");

                    b.ToTable("LawyerPersonalHolidays");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.LawyerProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BarCouncilNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Bio")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("ConsultationFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Court")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("LawyerProfiles");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.LawyerTimeSlotConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BufferTimeMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("LawyerProfileId")
                        .HasColumnType("int");

                    b.Property<int>("SessionDurationMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LawyerProfileId")
                        .IsUnique();

                    b.ToTable("LawyerTimeSlotConfigurations");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.LawyerWorkingHours", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsWorking")
                        .HasColumnType("bit");

                    b.Property<int>("LawyerProfileId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("LawyerProfileId", "DayOfWeek");

                    b.ToTable("LawyerWorkingHours");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.MasterHoliday", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AppliesYearly")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("HolidayDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HolidayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("MasterHolidays");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.Proposal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ClientNote")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DealId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<bool>("IsNegotiable")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DealId");

                    b.ToTable("Proposals");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.Publication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LawyerProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LawyerProfileId");

                    b.ToTable("Publications");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<int>("ClientProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("LawyerProfileId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.HasIndex("ClientProfileId");

                    b.HasIndex("LawyerProfileId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.StaffProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("LawyerProfileId")
                        .HasColumnType("int");

                    b.Property<string>("StaffRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LawyerProfileId");

                    b.HasIndex("UserId");

                    b.ToTable("StaffProfiles");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.StaffTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedToStaffProfileId")
                        .HasColumnType("int");

                    b.Property<int?>("CaseId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LawyerProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffNote")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToStaffProfileId");

                    b.HasIndex("CaseId");

                    b.HasIndex("LawyerProfileId");

                    b.ToTable("StaffTasks");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LegalConnect.API.Entities.Appointment", b =>
                {
                    b.HasOne("LegalConnect.API.Entities.ClientProfile", "ClientProfile")
                        .WithMany("Appointments")
                        .HasForeignKey("ClientProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LegalConnect.API.Entities.LawyerProfile", "LawyerProfile")
                        .WithMany("Appointments")
                        .HasForeignKey("LawyerProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClientProfile");

                    b.Navigation("LawyerProfile");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.Case", b =>
                {
                    b.HasOne("LegalConnect.API.Entities.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LegalConnect.API.Entities.ClientProfile", "ClientProfile")
                        .WithMany("Cases")
                        .HasForeignKey("ClientProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LegalConnect.API.Entities.Deal", "Deal")
                        .WithMany()
                        .HasForeignKey("DealId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LegalConnect.API.Entities.LawyerClient", "LawyerClient")
                        .WithMany("Cases")
                        .HasForeignKey("LawyerClientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LegalConnect.API.Entities.LawyerProfile", "LawyerProfile")
                        .WithMany("Cases")
                        .HasForeignKey("LawyerProfileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Appointment");

                    b.Navigation("ClientProfile");

                    b.Navigation("Deal");

                    b.Navigation("LawyerClient");

                    b.Navigation("LawyerProfile");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.CaseActivity", b =>
                {
                    b.HasOne("LegalConnect.API.Entities.Case", "Case")
                        .WithMany("Activities")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LegalConnect.API.Entities.ApplicationUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.CaseActivityDocument", b =>
                {
                    b.HasOne("LegalConnect.API.Entities.CaseActivity", "CaseActivity")
                        .WithMany("LinkedDocuments")
                        .HasForeignKey("CaseActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LegalConnect.API.Entities.CaseDocument", "CaseDocument")
                        .WithMany()
                        .HasForeignKey("CaseDocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CaseActivity");

                    b.Navigation("CaseDocument");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.CaseDocument", b =>
                {
                    b.HasOne("LegalConnect.API.Entities.Case", "Case")
                        .WithMany("Documents")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LegalConnect.API.Entities.ApplicationUser", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.CaseDocumentLawyerShare", b =>
                {
                    b.HasOne("LegalConnect.API.Entities.CaseDocument", "CaseDocument")
                        .WithMany("LawyerShares")
                        .HasForeignKey("CaseDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LegalConnect.API.Entities.LawyerProfile", "LawyerProfile")
                        .WithMany()
                        .HasForeignKey("LawyerProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CaseDocument");

                    b.Navigation("LawyerProfile");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.CaseLawyer", b =>
                {
                    b.HasOne("LegalConnect.API.Entities.Case", "Case")
                        .WithMany("CaseLawyers")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LegalConnect.API.Entities.LawyerProfile", "LawyerProfile")
                        .WithMany("CaseLawyers")
                        .HasForeignKey("LawyerProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("LawyerProfile");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.CaseResult", b =>
                {
                    b.HasOne("LegalConnect.API.Entities.LawyerProfile", "LawyerProfile")
                        .WithMany("CaseResults")
                        .HasForeignKey("LawyerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LawyerProfile");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.CaseStaff", b =>
                {
                    b.HasOne("LegalConnect.API.Entities.Case", "Case")
                        .WithMany("CaseStaffs")
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LegalConnect.API.Entities.StaffProfile", "StaffProfile")
                        .WithMany("CaseStaffs")
                        .HasForeignKey("StaffProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("StaffProfile");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.Certification", b =>
                {
                    b.HasOne("LegalConnect.API.Entities.LawyerProfile", "LawyerProfile")
                        .WithMany("Certifications")
                        .HasForeignKey("LawyerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LawyerProfile");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.ClientLawyerRequest", b =>
                {
                    b.HasOne("LegalConnect.API.Entities.ClientProfile", "ClientProfile")
                        .WithMany("LawyerRequests")
                        .HasForeignKey("ClientProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LegalConnect.API.Entities.LawyerProfile", "LawyerProfile")
                        .WithMany("IncomingRequests")
                        .HasForeignKey("LawyerProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClientProfile");

                    b.Navigation("LawyerProfile");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.ClientProfile", b =>
                {
                    b.HasOne("LegalConnect.API.Entities.ApplicationUser", "User")
                        .WithOne("ClientProfile")
                        .HasForeignKey("LegalConnect.API.Entities.ClientProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.Deal", b =>
                {
                    b.HasOne("LegalConnect.API.Entities.ClientProfile", "ClientProfile")
                        .WithMany()
                        .HasForeignKey("ClientProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LegalConnect.API.Entities.HireRequest", "HireRequest")
                        .WithOne("Deal")
                        .HasForeignKey("LegalConnect.API.Entities.Deal", "HireRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LegalConnect.API.Entities.LawyerProfile", "LawyerProfile")
                        .WithMany()
                        .HasForeignKey("LawyerProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClientProfile");

                    b.Navigation("HireRequest");

                    b.Navigation("LawyerProfile");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.Experience", b =>
                {
                    b.HasOne("LegalConnect.API.Entities.LawyerProfile", "LawyerProfile")
                        .WithMany("Experiences")
                        .HasForeignKey("LawyerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LawyerProfile");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.HireRequest", b =>
                {
                    b.HasOne("LegalConnect.API.Entities.ClientProfile", "ClientProfile")
                        .WithMany("HireRequests")
                        .HasForeignKey("ClientProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LegalConnect.API.Entities.LawyerProfile", "LawyerProfile")
                        .WithMany("HireRequests")
                        .HasForeignKey("LawyerProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClientProfile");

                    b.Navigation("LawyerProfile");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.HireRequestMessage", b =>
                {
                    b.HasOne("LegalConnect.API.Entities.HireRequest", "HireRequest")
                        .WithMany("Messages")
                        .HasForeignKey("HireRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LegalConnect.API.Entities.ApplicationUser", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HireRequest");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.Invoice", b =>
                {
                    b.HasOne("LegalConnect.API.Entities.Deal", "Deal")
                        .WithMany("Invoices")
                        .HasForeignKey("DealId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LegalConnect.API.Entities.Proposal", "Proposal")
                        .WithMany("Invoices")
                        .HasForeignKey("ProposalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Deal");

                    b.Navigation("Proposal");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.LawyerBlackoutBlock", b =>
                {
                    b.HasOne("LegalConnect.API.Entities.LawyerProfile", "LawyerProfile")
                        .WithMany("BlackoutBlocks")
                        .HasForeignKey("LawyerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LawyerProfile");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.LawyerClient", b =>
                {
                    b.HasOne("LegalConnect.API.Entities.ClientProfile", "ClientProfile")
                        .WithMany("LawyerClients")
                        .HasForeignKey("ClientProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LegalConnect.API.Entities.Appointment", "FirstAppointment")
                        .WithMany()
                        .HasForeignKey("FirstAppointmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LegalConnect.API.Entities.LawyerProfile", "LawyerProfile")
                        .WithMany("LawyerClients")
                        .HasForeignKey("LawyerProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClientProfile");

                    b.Navigation("FirstAppointment");

                    b.Navigation("LawyerProfile");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.LawyerHolidayPreference", b =>
                {
                    b.HasOne("LegalConnect.API.Entities.LawyerProfile", "LawyerProfile")
                        .WithMany("HolidayPreferences")
                        .HasForeignKey("LawyerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LegalConnect.API.Entities.MasterHoliday", "MasterHoliday")
                        .WithMany("LawyerPreferences")
                        .HasForeignKey("MasterHolidayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LawyerProfile");

                    b.Navigation("MasterHoliday");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.LawyerInvoiceSettings", b =>
                {
                    b.HasOne("LegalConnect.API.Entities.LawyerProfile", "LawyerProfile")
                        .WithOne("InvoiceSettings")
                        .HasForeignKey("LegalConnect.API.Entities.LawyerInvoiceSettings", "LawyerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LawyerProfile");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.LawyerPersonalHoliday", b =>
                {
                    b.HasOne("LegalConnect.API.Entities.LawyerProfile", "LawyerProfile")
                        .WithMany("PersonalHolidays")
                        .HasForeignKey("LawyerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LawyerProfile");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.LawyerProfile", b =>
                {
                    b.HasOne("LegalConnect.API.Entities.Category", "Category")
                        .WithMany("Lawyers")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LegalConnect.API.Entities.ApplicationUser", "User")
                        .WithOne("LawyerProfile")
                        .HasForeignKey("LegalConnect.API.Entities.LawyerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.LawyerTimeSlotConfiguration", b =>
                {
                    b.HasOne("LegalConnect.API.Entities.LawyerProfile", "LawyerProfile")
                        .WithOne("TimeSlotConfiguration")
                        .HasForeignKey("LegalConnect.API.Entities.LawyerTimeSlotConfiguration", "LawyerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LawyerProfile");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.LawyerWorkingHours", b =>
                {
                    b.HasOne("LegalConnect.API.Entities.LawyerProfile", "LawyerProfile")
                        .WithMany("WorkingHours")
                        .HasForeignKey("LawyerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LawyerProfile");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.Proposal", b =>
                {
                    b.HasOne("LegalConnect.API.Entities.Deal", "Deal")
                        .WithMany("Proposals")
                        .HasForeignKey("DealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deal");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.Publication", b =>
                {
                    b.HasOne("LegalConnect.API.Entities.LawyerProfile", "LawyerProfile")
                        .WithMany("Publications")
                        .HasForeignKey("LawyerProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LawyerProfile");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.Review", b =>
                {
                    b.HasOne("LegalConnect.API.Entities.Appointment", "Appointment")
                        .WithOne("Review")
                        .HasForeignKey("LegalConnect.API.Entities.Review", "AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LegalConnect.API.Entities.ClientProfile", "ClientProfile")
                        .WithMany("Reviews")
                        .HasForeignKey("ClientProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LegalConnect.API.Entities.LawyerProfile", "LawyerProfile")
                        .WithMany("Reviews")
                        .HasForeignKey("LawyerProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("ClientProfile");

                    b.Navigation("LawyerProfile");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.StaffProfile", b =>
                {
                    b.HasOne("LegalConnect.API.Entities.LawyerProfile", "LawyerProfile")
                        .WithMany("StaffMembers")
                        .HasForeignKey("LawyerProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LegalConnect.API.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LawyerProfile");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.StaffTask", b =>
                {
                    b.HasOne("LegalConnect.API.Entities.StaffProfile", "AssignedTo")
                        .WithMany("AssignedTasks")
                        .HasForeignKey("AssignedToStaffProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LegalConnect.API.Entities.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("LegalConnect.API.Entities.LawyerProfile", "LawyerProfile")
                        .WithMany()
                        .HasForeignKey("LawyerProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedTo");

                    b.Navigation("Case");

                    b.Navigation("LawyerProfile");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("LegalConnect.API.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("LegalConnect.API.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LegalConnect.API.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("LegalConnect.API.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LegalConnect.API.Entities.ApplicationUser", b =>
                {
                    b.Navigation("ClientProfile");

                    b.Navigation("LawyerProfile");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.Appointment", b =>
                {
                    b.Navigation("Review");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.Case", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("CaseLawyers");

                    b.Navigation("CaseStaffs");

                    b.Navigation("Documents");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.CaseActivity", b =>
                {
                    b.Navigation("LinkedDocuments");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.CaseDocument", b =>
                {
                    b.Navigation("LawyerShares");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.Category", b =>
                {
                    b.Navigation("Lawyers");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.ClientProfile", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Cases");

                    b.Navigation("HireRequests");

                    b.Navigation("LawyerClients");

                    b.Navigation("LawyerRequests");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.Deal", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("Proposals");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.HireRequest", b =>
                {
                    b.Navigation("Deal");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.LawyerClient", b =>
                {
                    b.Navigation("Cases");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.LawyerProfile", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("BlackoutBlocks");

                    b.Navigation("CaseLawyers");

                    b.Navigation("CaseResults");

                    b.Navigation("Cases");

                    b.Navigation("Certifications");

                    b.Navigation("Experiences");

                    b.Navigation("HireRequests");

                    b.Navigation("HolidayPreferences");

                    b.Navigation("IncomingRequests");

                    b.Navigation("InvoiceSettings");

                    b.Navigation("LawyerClients");

                    b.Navigation("PersonalHolidays");

                    b.Navigation("Publications");

                    b.Navigation("Reviews");

                    b.Navigation("StaffMembers");

                    b.Navigation("TimeSlotConfiguration");

                    b.Navigation("WorkingHours");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.MasterHoliday", b =>
                {
                    b.Navigation("LawyerPreferences");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.Proposal", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("LegalConnect.API.Entities.StaffProfile", b =>
                {
                    b.Navigation("AssignedTasks");

                    b.Navigation("CaseStaffs");
                });
#pragma warning restore 612, 618
        }
    }
}
